### ISSUE TITLE
Broken in Moodle 3.1?

### ISSUE THREAD

**Issue by comete-upo** [DBezemer/moodle-local_analytics#6]
We updated Moodle from 2.7 to 3.1 and the plugin doesn't work anymore.
It seems that $CFG->additionalhtmlhead modification is not taken into account at runtime, which is a shame.
In a hurry, we used your code to add Piwik to our theme, but maybe its fixable?
Thanks anyway for the URLs cleanup!

**Comment by DBezemer** [comment]
@comete-upo the plugin is maintained by @bmbrands now at https://github.com/bmbrands/moodle-local_analytics
